openapi: 3.0.0
info:
  title: API de Gestion des Produits
  version: 1.0.0
  description: Documentation de l'API pour la gestion des produits et des commandes
servers:
  - url: http://localhost:5000
paths:
  /produits:
    post:
      summary: Ajouter un produit
      tags: [Produits]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                libelle:
                  type: string
                description:
                  type: string
                image:
                  type: string
                price:
                  type: number
                qte:
                  type: integer
                idUser:
                  type: integer
      responses:
        '200':
          description: Produit créé avec succès
        '400':
          description: Erreur de validation ou utilisateur non trouvé
        '500':
          description: Erreur interne du serveur

  /produits/{id}:
    put:
      summary: Mettre à jour un produit
      tags: [Produits]
      parameters:
        - name: id
          in: path
          required: true
          description: ID du produit à mettre à jour
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                libelle:
                  type: string
                description:
                  type: string
                image:
                  type: string
                price:
                  type: number
                qte:
                  type: integer
      responses:
        '200':
          description: Produit mis à jour avec succès
        '400':
          description: Erreur de validation
        '500':
          description: Erreur interne du serveur

  /produits/user/{idActor}:
    get:
      summary: Récupérer les produits d'un utilisateur
      tags: [Produits]
      parameters:
        - name: idActor
          in: path
          required: true
          description: ID de l'utilisateur
          schema:
            type: integer
      responses:
        '200':
          description: Produits récupérés avec succès
        '500':
          description: Erreur interne du serveur

  /commandes:
    post:
      summary: Créer une nouvelle commande
      tags: [Commandes]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                idUser:
                  type: integer
      responses:
        '200':
          description: Commande créée avec succès
        '400':
          description: Erreur de validation
        '500':
          description: Erreur interne du serveur

  /commandes/{id}/valider:
    put:
      summary: Valider une commande
      tags: [Commandes]
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la commande à valider
          schema:
            type: integer
      responses:
        '200':
          description: Commande validée avec succès
        '400':
          description: Erreur de validation
        '500':
          description: Erreur interne du serveur

  /commandes/user/{idUser}:
    get:
      summary: Récupérer les commandes d'un utilisateur
      tags: [Commandes]
      parameters:
        - name: idUser
          in: path
          required: true
          description: ID de l'utilisateur
          schema:
            type: integer
      responses:
        '200':
          description: Commandes récupérées avec succès
        '500':
          description: Erreur interne du serveur